name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/ci.yml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-material-

      - run: pip install mkdocs-material ## Read more about themes here https://www.mkdocs.org/user-guide/choosing-your-theme/
      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 ## https://github.com/peaceiris/actions-gh-pages/tree/v4/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: mkdocs-template.jonathan.com.ar

  
